# Generated by Django 2.2.12 on 2020-04-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200413_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/download.jpeg', upload_to='profile_pics/'),
        ),
    ]
