# Generated by Django 2.2.12 on 2020-04-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productviewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productviewcount',
            name='session',
        ),
    ]
